// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoFinalDotNet8.Data;

#nullable disable

namespace ProyectoFinalDotNet8.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231202223920_Agregando restricciones para Menu y despacho")]
    partial class AgregandorestriccionesparaMenuydespacho
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProyectoFinalDotNet8.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellidos")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Shared.Models.CentrosEducativos", b =>
                {
                    b.Property<int>("CentroEducativoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadMatricula")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoDistrital")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoRegional")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CentroEducativoId");

                    b.ToTable("CentrosEducativos");
                });

            modelBuilder.Entity("Shared.Models.Comentarios", b =>
                {
                    b.Property<int>("ComentarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComentarioTexto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("MenuId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nota")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ComentarioId");

                    b.HasIndex("MenuId");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("Shared.Models.Comidas", b =>
                {
                    b.Property<int>("ComidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoComidaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ComidaId");

                    b.ToTable("Comidas");
                });

            modelBuilder.Entity("Shared.Models.Despacho", b =>
                {
                    b.Property<int>("DespachoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CentroEducativoId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ConfirmacionEntrega")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRecepcion")
                        .HasColumnType("TEXT");

                    b.Property<int>("MenuId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecibidoPor")
                        .HasColumnType("TEXT");

                    b.HasKey("DespachoId");

                    b.ToTable("Despachos");
                });

            modelBuilder.Entity("Shared.Models.DespachoDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadDecomida")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComidaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DespachoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalleId");

                    b.HasIndex("DespachoId");

                    b.ToTable("DespachoDetalles");
                });

            modelBuilder.Entity("Shared.Models.Distritos", b =>
                {
                    b.Property<int>("DistritoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoDistrito")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoRegional")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreDistrital")
                        .HasColumnType("TEXT");

                    b.HasKey("DistritoId");

                    b.ToTable("Distritos");

                    b.HasData(
                        new
                        {
                            DistritoId = 1,
                            CodigoDistrito = "01",
                            CodigoRegional = "06",
                            NombreDistrital = "José Contreras"
                        },
                        new
                        {
                            DistritoId = 2,
                            CodigoDistrito = "02",
                            CodigoRegional = "06",
                            NombreDistrital = "Constanza"
                        },
                        new
                        {
                            DistritoId = 3,
                            CodigoDistrito = "03",
                            CodigoRegional = "07",
                            NombreDistrital = "Villa Riva"
                        },
                        new
                        {
                            DistritoId = 4,
                            CodigoDistrito = "04",
                            CodigoRegional = "07",
                            NombreDistrital = "Tenares"
                        },
                        new
                        {
                            DistritoId = 5,
                            CodigoDistrito = "03",
                            CodigoRegional = "08",
                            NombreDistrital = "Santiago Sur-Este"
                        },
                        new
                        {
                            DistritoId = 6,
                            CodigoDistrito = "04",
                            CodigoRegional = "08",
                            NombreDistrital = "Santiago Noroeste"
                        },
                        new
                        {
                            DistritoId = 7,
                            CodigoDistrito = "05",
                            CodigoRegional = "08",
                            NombreDistrital = "Santiago Centro-Oeste"
                        },
                        new
                        {
                            DistritoId = 8,
                            CodigoDistrito = "05",
                            CodigoRegional = "10",
                            NombreDistrital = "Boca Chica"
                        },
                        new
                        {
                            DistritoId = 9,
                            CodigoDistrito = "06",
                            CodigoRegional = "10",
                            NombreDistrital = "Mendoza"
                        },
                        new
                        {
                            DistritoId = 10,
                            CodigoDistrito = "07",
                            CodigoRegional = "10",
                            NombreDistrital = "San Antonio De Guerra"
                        },
                        new
                        {
                            DistritoId = 11,
                            CodigoDistrito = "01",
                            CodigoRegional = "11",
                            NombreDistrital = "Sosua"
                        },
                        new
                        {
                            DistritoId = 12,
                            CodigoDistrito = "02",
                            CodigoRegional = "11",
                            NombreDistrital = "Puerto Plata"
                        },
                        new
                        {
                            DistritoId = 13,
                            CodigoDistrito = "01",
                            CodigoRegional = "12",
                            NombreDistrital = "Higuey"
                        },
                        new
                        {
                            DistritoId = 14,
                            CodigoDistrito = "01",
                            CodigoRegional = "14",
                            NombreDistrital = "Nagua"
                        },
                        new
                        {
                            DistritoId = 15,
                            CodigoDistrito = "01",
                            CodigoRegional = "16",
                            NombreDistrital = "Cotui"
                        },
                        new
                        {
                            DistritoId = 16,
                            CodigoDistrito = "04",
                            CodigoRegional = "16",
                            NombreDistrital = "Bonao Suroeste"
                        },
                        new
                        {
                            DistritoId = 17,
                            CodigoDistrito = "03",
                            CodigoRegional = "01",
                            NombreDistrital = "Barahona"
                        },
                        new
                        {
                            DistritoId = 18,
                            CodigoDistrito = "05",
                            CodigoRegional = "02",
                            NombreDistrital = "San Juan Este"
                        },
                        new
                        {
                            DistritoId = 19,
                            CodigoDistrito = "01",
                            CodigoRegional = "03",
                            NombreDistrital = "Azua"
                        },
                        new
                        {
                            DistritoId = 20,
                            CodigoDistrito = "03",
                            CodigoRegional = "03",
                            NombreDistrital = "San Jose De Ocoa"
                        },
                        new
                        {
                            DistritoId = 21,
                            CodigoDistrito = "05",
                            CodigoRegional = "03",
                            NombreDistrital = "Nizao"
                        },
                        new
                        {
                            DistritoId = 22,
                            CodigoDistrito = "04",
                            CodigoRegional = "04",
                            NombreDistrital = "Villa Altagracia"
                        },
                        new
                        {
                            DistritoId = 23,
                            CodigoDistrito = "06",
                            CodigoRegional = "04",
                            NombreDistrital = "Haina"
                        },
                        new
                        {
                            DistritoId = 24,
                            CodigoDistrito = "07",
                            CodigoRegional = "04",
                            NombreDistrital = "San Gregorio De Nigua"
                        },
                        new
                        {
                            DistritoId = 25,
                            CodigoDistrito = "03",
                            CodigoRegional = "05",
                            NombreDistrital = "La Romana"
                        },
                        new
                        {
                            DistritoId = 26,
                            CodigoDistrito = "04",
                            CodigoRegional = "05",
                            NombreDistrital = "Hato Mayor"
                        },
                        new
                        {
                            DistritoId = 27,
                            CodigoDistrito = "06",
                            CodigoRegional = "05",
                            NombreDistrital = "Consuelo"
                        },
                        new
                        {
                            DistritoId = 28,
                            CodigoDistrito = "10",
                            CodigoRegional = "05",
                            NombreDistrital = "Guaymate"
                        });
                });

            modelBuilder.Entity("Shared.Models.Menu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Imagen")
                        .HasColumnType("BLOB");

                    b.HasKey("MenuId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("Shared.Models.MenuDetalles", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComidaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MenuId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalleId");

                    b.HasIndex("MenuId");

                    b.ToTable("MenuDetalles");
                });

            modelBuilder.Entity("Shared.Models.Regiones", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoRegional")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreRegion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RegionId");

                    b.ToTable("Regiones");

                    b.HasData(
                        new
                        {
                            RegionId = 1,
                            CodigoRegional = "06",
                            NombreRegion = "La Vega"
                        },
                        new
                        {
                            RegionId = 2,
                            CodigoRegional = "07",
                            NombreRegion = "San Francisco de Macorís"
                        },
                        new
                        {
                            RegionId = 3,
                            CodigoRegional = "08",
                            NombreRegion = "Santiago"
                        },
                        new
                        {
                            RegionId = 4,
                            CodigoRegional = "10",
                            NombreRegion = "Santo Domingo"
                        },
                        new
                        {
                            RegionId = 5,
                            CodigoRegional = "11",
                            NombreRegion = "Puerto Plata"
                        },
                        new
                        {
                            RegionId = 6,
                            CodigoRegional = "12",
                            NombreRegion = "Higuey"
                        },
                        new
                        {
                            RegionId = 7,
                            CodigoRegional = "14",
                            NombreRegion = "Nagua"
                        },
                        new
                        {
                            RegionId = 8,
                            CodigoRegional = "16",
                            NombreRegion = "Cotui"
                        },
                        new
                        {
                            RegionId = 9,
                            CodigoRegional = "01",
                            NombreRegion = "Barahona"
                        },
                        new
                        {
                            RegionId = 10,
                            CodigoRegional = "02",
                            NombreRegion = "San Juan De La Maguana"
                        },
                        new
                        {
                            RegionId = 11,
                            CodigoRegional = "03",
                            NombreRegion = "Azua"
                        },
                        new
                        {
                            RegionId = 12,
                            CodigoRegional = "04",
                            NombreRegion = "San Cristobal"
                        },
                        new
                        {
                            RegionId = 13,
                            CodigoRegional = "05",
                            NombreRegion = "San Pedro De Macoris"
                        });
                });

            modelBuilder.Entity("Shared.Models.TiposComidas", b =>
                {
                    b.Property<int>("TipoComidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.HasKey("TipoComidaId");

                    b.ToTable("TiposComidas");

                    b.HasData(
                        new
                        {
                            TipoComidaId = 1,
                            Tipo = "Carbohidratos"
                        },
                        new
                        {
                            TipoComidaId = 2,
                            Tipo = "Proteinas"
                        },
                        new
                        {
                            TipoComidaId = 3,
                            Tipo = "Grasas"
                        },
                        new
                        {
                            TipoComidaId = 4,
                            Tipo = "Fibras"
                        },
                        new
                        {
                            TipoComidaId = 5,
                            Tipo = "Minerales"
                        },
                        new
                        {
                            TipoComidaId = 6,
                            Tipo = "Vitaminas"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ProyectoFinalDotNet8.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ProyectoFinalDotNet8.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoFinalDotNet8.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ProyectoFinalDotNet8.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shared.Models.Comentarios", b =>
                {
                    b.HasOne("Shared.Models.Menu", null)
                        .WithMany("ComenentarioDetalle")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shared.Models.DespachoDetalle", b =>
                {
                    b.HasOne("Shared.Models.Despacho", null)
                        .WithMany("DespachoDetalles")
                        .HasForeignKey("DespachoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shared.Models.MenuDetalles", b =>
                {
                    b.HasOne("Shared.Models.Menu", null)
                        .WithMany("MenuDetalles")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shared.Models.Despacho", b =>
                {
                    b.Navigation("DespachoDetalles");
                });

            modelBuilder.Entity("Shared.Models.Menu", b =>
                {
                    b.Navigation("ComenentarioDetalle");

                    b.Navigation("MenuDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
